In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option('display.max_columns', None)

In [2]:
original_df = pd.read_csv('4.3_dataset_clean_v2.csv')
original_df.head()

,link,address,apartment_name,sector,price,price_sqft,super_area,bedrooms,bathroom,balcony,additional_rooms,age_possession,floor,floor_num,total_floors,furnishing_type,facing,num_parking,features,servant_room,study_room,pooja_room,store_room,luxury_score,luxury_category,parking
0,https://www.99acres.com/2-bhk-bedroom-apartmen...,"Bharat Residency\nJharsa, Gurgaon",bharat residency,jharsa,0.70,5477.3,1278.0000,2,2,2,Store Room,1 to 5 year old,Ground of 4 Floors,0,4,Semifurnished,na,1 Open,"['Security / Fire Alarm', 'Lift(s)', 'High Cei...",0,0,0,1,21,medium,1
1,https://www.99acres.com/2-bhk-bedroom-apartmen...,"GLS Arawali Homes\nSohna, Gurgaon",gls arawali homes,sohna,0.38,5569.0,682.3526,2,2,2,Others,1 to 5 year old,6th of 13 Floors,6,13,Semifurnished,East,"1 Covered, 1 Open","['Security / Fire Alarm', 'Power Back-up', 'Fe...",0,0,0,0,35,medium,2
2,https://www.99acres.com/2-bhk-bedroom-apartmen...,"CHD Avenue 71\nSector 71, Gurgaon",chd avenue 71,sector 71,1.35,11268.8,1198.0000,2,2,2,NaN,10+ year old,1st of 14 Floors,1,14,Unfurnished,North,1 Covered,"['Centrally Air Conditioned', 'Water purifier'...",0,0,0,0,71,high,1
3,https://www.99acres.com/4-bhk-bedroom-apartmen...,"signature avenue\nSector 82, Gurgaon",signature avenue,sector 82,3.40,10493.8,3240.0000,4,4,2,"Pooja Room,Servant Room",0 to 1 year old,4th of 4 Floors,4,4,Furnished,North-East,2 Covered,"['Power Back-up', 'Lift(s)', 'Water purifier',...",1,0,1,0,28,medium,2
4,https://www.99acres.com/2-bhk-bedroom-apartmen...,"Signature Global Park\nSohna, Gurgaon",signature global park,sohna,0.95,8920.2,1065.0000,2,2,2,NaN,0 to 1 year old,1st of 4 Floors,1,4,Semifurnished,na,1 Covered,"['Lift(s)', 'Swimming Pool', 'Park', 'Fitness ...",0,0,0,0,18,low,1

In [3]:
df = original_df.drop(columns = ['link','address','additional_rooms','floor', 'num_parking','features'])
df.head()

,apartment_name,sector,price,price_sqft,super_area,bedrooms,bathroom,balcony,age_possession,floor_num,total_floors,furnishing_type,facing,servant_room,study_room,pooja_room,store_room,luxury_score,luxury_category,parking
0,bharat residency,jharsa,0.70,5477.3,1278.0000,2,2,2,1 to 5 year old,0,4,Semifurnished,na,0,0,0,1,21,medium,1
1,gls arawali homes,sohna,0.38,5569.0,682.3526,2,2,2,1 to 5 year old,6,13,Semifurnished,East,0,0,0,0,35,medium,2
2,chd avenue 71,sector 71,1.35,11268.8,1198.0000,2,2,2,10+ year old,1,14,Unfurnished,North,0,0,0,0,71,high,1
3,signature avenue,sector 82,3.40,10493.8,3240.0000,4,4,2,0 to 1 year old,4,4,Furnished,North-East,1,0,1,0,28,medium,2
4,signature global park,sohna,0.95,8920.2,1065.0000,2,2,2,0 to 1 year old,1,4,Semifurnished,na,0,0,0,0,18,low,1

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5592 entries, 0 to 5591
Data columns (total 20 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   apartment_name   5592 non-null   object
 1   sector           5592 non-null   object
 2   price            5592 non-null   float64
 3   price_sqft       5592 non-null   float64
 4   super_area       5592 non-null   float64
 5   bedrooms         5592 non-null   int64
 6   bathroom         5592 non-null   int64
 7   balcony          5592 non-null   object
 8   age_possession   5592 non-null   object
 9   floor_num        5592 non-null   int64
 10  total_floors     5592 non-null   int64
 11  furnishing_type  5592 non-null   object
 12  facing           5592 non-null   object
 13  servant_room     5592 non-null   int64
 14  study_room       5592 non-null   int64
 15  pooja_room       5592 non-null   int64
 16  store_room       5592 non-null   int64
 17  luxury_score     5592 non-null   int64
 18  luxury_category  5592 non-null   object
 19  parking          5592 non-null   int64
dtypes: float64(3), int64(10), object(7)
memory usage: 873.9+ KB

In [5]:
import sweetviz as sv

# Create and generate the report
feature_config = sv.FeatureConfig()
report = sv.analyze(source=df, 
                    target_feat='price',
                    feat_cfg=feature_config)

# Show the report in an HTML file
report.show_html(filepath="sweetviz_report.html",
                 layout='vertical')

/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm
Done! Use 'show' commands to display/save.   |██████████| [100%]   00:00 -> (00:00 left)

Report sweetviz_report.html was generated! NOTEBOOK/COLAB USERS: the web browser MAY not pop up, regardless, the report IS saved in your notebook/colab files.